# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.srcs/sources_1/ip/qdma_0/qdma_0.xci
# IP: The module: 'qdma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/qdma_0_pcie4_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] -quiet

# IP: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/ip_0/qdma_0_pcie4_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip_gt || ORIG_REF_NAME==qdma_0_pcie4_ip_gt} -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/ip_0/synth/qdma_0_pcie4_ip_gt_ooc.xdc

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/ip_0/synth/qdma_0_pcie4_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip_gt || ORIG_REF_NAME==qdma_0_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/qdma_0_pcie4_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/source/ip_pcie4_uscale_plus_impl_x0y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/synth/qdma_0_pcie4_ip_ooc.xdc

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/synth/qdma_0_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/source/ip_pcie4_uscale_plus_x0y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/qdma_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/source/qdma_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/synth/qdma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.srcs/sources_1/ip/qdma_0/qdma_0.xci
# IP: The module: 'qdma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/qdma_0_pcie4_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] -quiet

# IP: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/ip_0/qdma_0_pcie4_ip_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip_gt || ORIG_REF_NAME==qdma_0_pcie4_ip_gt} -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/ip_0/synth/qdma_0_pcie4_ip_gt_ooc.xdc

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/ip_0/synth/qdma_0_pcie4_ip_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip_gt || ORIG_REF_NAME==qdma_0_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/qdma_0_pcie4_ip_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/source/ip_pcie4_uscale_plus_impl_x0y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/synth/qdma_0_pcie4_ip_ooc.xdc

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/synth/qdma_0_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/ip_0/source/ip_pcie4_uscale_plus_x0y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==qdma_0_pcie4_ip || ORIG_REF_NAME==qdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/qdma_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/source/qdma_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ncherry/qdma_no_sriov/qdma_0_ex/qdma_0_ex.gen/sources_1/ip/qdma_0/synth/qdma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
